[package]
name = "rlcore"
version = "0.1.0"
edition = "2018"

[features]

[dependencies]
snow2d = { path = "../snow2d" }
igri = { path = "../snow2d/crates/igri/igri" }

serde = "1.0.127"

auto_ops = "0.3.0"
derivative = "2.2.0"
dyn-clone = "1.0.4"
log = "0.4.14"
downcast-rs = "1.2.0"

