[package]
name = "snowrl"
version = "0.1.0"
authors = ["toyboot4e <toyboot4e@gmail.com>"]
edition = "2018"

# exclude = [""]
# keywords = ["book", "ssg", "asciidoc"]
# license = "MIT"
# repository = "https://github.com/toyboot4e/snowrl"
# description = ""

[workspace]
members = [
    "crates/snow2d",
    "crates/snow2d/rokol",
    "crates/snow2d/xdl",
    "crates/rlbox",
]
exclude = [
    "crates/snow2d"
]

[dependencies]
rokol = { path = "crates/snow2d/rokol", features = ["glcore33"] }
snow2d = { path = "crates/snow2d" }
rlbox = { path = "crates/rlbox" }

image = "0.23.12"
glam = "0.11.2"
tiled = "0.9.3"

log = "0.4.11"
env_logger = "0.8.2"
anyhow = "1.0.37"
thiserror = "1.0.21"

auto_ops = "0.1.0"
bitflags = "1.2.1"
once_cell = "1.5.2"
rand = "0.8.0"
downcast-rs = "1.2.0"

[build-dependencies]
convert_case = "0.4.0"

