[package]
name = "snow2d_derive"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[features]
dummy = []

[dependencies]
darling = "0.12.4"
proc-macro2 = "1.0.26"
quote = "1.0.9"
syn = "1.0.70"
synstructure = "0.12.4"
