[package]
name = "model"
version = "0.1.0"
edition = "2018"

[dependencies]
snow2d = { path = "../snow2d" }
rlcore = { path = "../rlcore" }
igri = { path = "../snow2d/crates/igri/igri" }

derivative = "2.2.0"
log = "0.4.14"
serde = "1.0.127"
dyn-clone = "1.0.4"

